# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06a83d451920beb0868605869c238f8031ce1ef3d4f4fc1b2650b90b9e65fd68b4990351df9db767ca0594ffcbeabc498f45f586b5ff37b8cb43b78de0931fe6

test:
  secret_key_base: 07071fbb903fdf04e23a606eb882b28e78ac05fa3c8d1e6fd125fc5954bb0f5e95bf307990d40b76d06eaaa70ac8f405c7fa8957af93180997d1ef8c11c220a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
